name: test-tp-ddp2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-assignments:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Build Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5
          arguments: build -x test
      - name: Test Assignment 1
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5
          arguments: :assignment1:test
